all:
	swipl -q -g puzzle:main -o main -c main.pl print_utils.pl parser.pl

test:
	swipl -q -g puzzle:main_test -o main -c main.pl print_utils.pl parser.pl


input:
	swipl -q -g start -o flp16-log -c input2.pl
