all:
	swipl -q -g puzzle:main -o flp17-log -c main.pl print_utils.pl parser.pl

test:
	swipl -q -g puzzle:main_test -o flp17-log-test -c main.pl print_utils.pl parser.pl

clean:
	rm -f flp17-log-test flp17-log

